In [4]:
from collections import Counter
import pandas as pd

In [22]:
with open('ciência_de_dados.txt', encoding = 'iso-8859-1') as file:
    texto = file.read()
    for char in '(),._/:\n':
        texto = texto.replace(char, ' ')
    c = Counter(texto.split())
print(c)

Counter({'de': 18, 'dados': 9, 'e': 7, 'o': 4, 'como': 4, 'em': 3, 'para': 3, 'a': 3, 'Ciência': 2, 'data': 2, 'é': 2, 'análise': 2, 'ou': 2, 'que': 2, 'insights': 2, 'tomadas': 2, 'machine': 2, 'learning': 2, 'áreas': 2, 'A': 2, 'ciência': 2, 'anos': 2, 'inglês': 1, 'science': 1, 'uma': 1, 'área': 1, 'interdisciplinar': 1, 'voltada': 1, 'estudo': 1, 'estruturados': 1, 'não': 1, 'visa': 1, 'extração': 1, 'conhecimento': 1, 'possíveis': 1, 'decisão': 1, 'maneira': 1, 'similar': 1, 'à': 1, 'mineração': 1, 'alia': 1, 'big': 1, 'além': 1, 'técnicas': 1, 'outras': 1, 'interdisciplinares': 1, 'estatística': 1, 'economia': 1, 'engenharia': 1, 'outros': 1, 'subcampos': 1, 'da': 1, 'computação': 1, 'banco': 1, 'agrupamentos': 1, 'cluster': 1, 'analysis': 1, 'um': 1, 'campo': 1, 'já': 1, 'existe': 1, 'há': 1, '30': 1, 'porém': 1, 'ganhou': 1, 'mais': 1, 'destaque': 1, 'nos': 1, 'últimos': 1, 'devido': 1, 'alguns': 1, 'fatores': 1, 'surgimento': 1, 'popularização': 1, 'do': 1, 'Big': 1, 'Data': 1, 'desenvolvimento': 1, 'pode': 1, 'por': 1, 'exemplo': 1, 'transformar': 1, 'essa': 1, 'grande': 1, 'quantidade': 1, 'brutos': 1, 'negócios': 1, 'com': 1, 'isso': 1, 'auxiliar': 1, 'empresas': 1, 'decisões': 1, 'atingir': 1, 'melhores': 1, 'resultados': 1, 'Fonte': 1, 'https': 1, 'pt': 1, 'wikipedia': 1, 'org': 1, 'wiki': 1, 'Ci%C3%AAncia': 1})

In [20]:
df = pd.DataFrame.from_dict(c, orient='index').reset_index()
df = df.rename(columns={'index': 'Word', 0:'Number'})
df.head(25)

                Word  Number
0            Ciência       2
1                 de      17
2              dados       8
3                 em       3
4             inglês       1
5               data       2
6            science       1
7                  é       2
8                uma       1
9               área       1
10  interdisciplinar       1
11           voltada       1
12              para       3
13                 o       4
14            estudo       1
15                 e       7
16                 a       3
17           análise       2
18      estruturados       1
19                ou       2
20               não       1
21               que       2
22              visa       1
23          extração       1
24      conhecimento       1